//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace DGX.Character.Anim
{
    public class FighterAnimation : ScriptableObject
    {
        public AnimationClip attackClip;
        public AnimationClip dieClip;
        public double impactTime;

        private AnimationState attackState;
        private AnimationState dieState;

        protected override void init ()
        {
            base.init ();
            attackState = ANIMATION[attackClip.name];
            dieState = ANIMATION [dieClip.name];
        }
        public void playingAttack()
        {
            ANIMATION.Play(attackClip.name);
        }
        public void playingDying()
        {
            ANIMATION.CrossFade(dieClip.name);
        }

        public bool isAttackAnimationEnded()
        {
            bool b = (attackState.time > 0.9 * attackState.length);
            return b;
        }
        public bool isDiePlaying()
        {
            bool b = ANIMATION.IsPlaying (dieClip.name);
            return b;
        }
        public bool isAttackPlaying()
        {
            bool b = ANIMATION.IsPlaying (attackClip.name);
            return b;
        }
        public bool isImpactTime()
        {
            bool b = attackState.time > attackState.length * impactTime && !isAttackAnimationEnded ();
            return b;
        }
        public bool isDieEnded()
        {
            bool b = (dieState.time > dieState.length * 0.9);
            return b;
        }
    }
}

