//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace DGX.Character.Controller
{
    public class PlayerFighterController : ScriptableObject
    {

        Fighter fighter;

        protected override void init ()
        {
            base.init ();
            fighter = GetComponent<Fighter> ();
        }
        public void Update ()
        {
            if (Input.GetKey (KeyCode.Space)) {
                fighter.onAttack();
            }
        }
    }
}

