//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityStandardAssets._2D;

namespace DGX._2D.Controller
{
	[RequireComponent (typeof (Player2D))]
	public class Animator2D : MonoBehaviour
	{
		public Player2D mPlayer2D;
		private Animator mAnimator;
		private bool mLookRight;

		private void Awake()
		{
			mPlayer2D = GetComponentInParent<Player2D>();
			mAnimator = GetComponent<Animator>();
			mLookRight = true;
		}

		private void FixedUpdate()
		{
			float inputX = mPlayer2D.INPUT.x;
			if (mLookRight) {
				if (inputX < 0) {
					mLookRight = false;
					flipAnimation();
				}
			} else {
				if (inputX > 0) {
					mLookRight = true;
					flipAnimation();
				}
			}
			mAnimator.SetFloat("speed", Math.Abs(mPlayer2D.VELOCITY.x));
			mAnimator.SetBool("Ground", mPlayer2D.isGrounded());
		}
		private void flipAnimation()
		{
			Vector3 scale = gameObject.transform.localScale;
			scale.x *= -1;
			gameObject.transform.localScale = scale;
		}
	}
}

