//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace DGX.Controller
{
    public class XBoxJoyStick : JoyStick
    {
        public XBoxJoyStick ()
            :base()
        {
        }

        public bool isX()
        {
            if (isAction0()) {
                return true;
            }
            return false;
        }
        public bool isY()
        {
            if (isAction3()) {
                return true;
            }
            return false;
        }
        public bool isA()
        {
            if (isAction1()) {
                return true;
            }
            return false;
        }
        public bool isB()
        {
            if (isAction2()) {
                return true;
            }
            return false;
        }
        public bool isLD()
        {
            if (isAction6()) {
                return true;
            }
            return false;
        }
        public bool isRD()
        {
            if (isAction7()) {
                return true;
            }
            return false;
        }
        public bool isLU()
        {
            if (isAction4()) {
                return true;
            }
            return false;
        }
        public bool isRU()
        {
            if (isAction5()) {
                return true;
            }
            return false;
        }
    }
}

