//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace DGX
{
    public class ScriptableObject : UnityEngine.MonoBehaviour
    {
        private float mElapsedTime;
        private Logger mLogger;
        public bool debug = false;
        

        public ScriptableObject ()
        {
            
        }

        public void Start () 
        {
            mLogger = new Logger(gameObject.name);
            //fighterAnimation = GetComponent<Character.Anim.FighterAnimation> ();
            init();
        }
        protected void rememberElapsedTime()
        {
            mElapsedTime = Time.deltaTime;
        }
        protected Animation ANIMATION
        {
            get { return GetComponent<Animation>();}
        }
        protected Logger LOGGER
        {
            get {return mLogger;}
        }
        protected virtual void init()
        {
            mLogger.DEBUG = debug;
        }
        protected float ELAPSED_TIME
        {
            get
            {
                return mElapsedTime;
            }
        }
    }
}

